### ISSUE TITLE
Please add TJM display on backoffice for consultant 

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#19]
![image](https://user-images.githubusercontent.com/42932849/71175510-07bd2180-2268-11ea-8441-4d9b80d76dad.png)
 
![image](https://user-images.githubusercontent.com/42932849/71175530-173c6a80-2268-11ea-81f1-538684e99d6e.png)

**Comment by khalid-elabbadi** [comment]
Fixed

**Comment by Laila-BENGHABRIT** [comment]
Still doesn't appear, i mean the TJM
![image](https://user-images.githubusercontent.com/42932849/71355116-57f4f600-257e-11ea-8cb7-6220972b21b3.png)

**Comment by Laila-BENGHABRIT** [comment]
DONE!
